attention: bahdanau
batch_size: 80
beam_width: 10
bidirectional: true
cell_type: lstm
dec.max_length: 50
dec.num_layers: 1
dec.style: bahdanau
dropout: 0.5
emb.init_scale: 0.01
emb.size: 256
emb.tied: true
enc.num_layers: 1
evaluate_every: -1
gen.l2_weight: 0.0
gen.lr: 0.002
gen.opt: adam
hidden.size: 256
inf.l2_weight: 0.0
inf.lr: 0.002
inf.opt: adam
kl.annealing_steps: 0
kl.free_nats: 10.0
latent.size: 32
length_penalty_factor: 1.0
lr.min: 5.0e-07
lr.reduce_cooldown: 2
lr.reduce_factor: 0.5
lr.reduce_patience: 3
max_gradient_norm: 4.0
max_sentence_length: 50
model.type: aevnmt
num_epochs: 10
patience: 2
posterior.type: PoG
print_every: 100
src: en
subword_token: '@@'
tgt: de
use_gpu: false
vocab.max_size: -1
vocab.min_freq: 0
vocab.shared: true
word_dropout: 0.0
