# Flag to indicate if the codebase is already translated to nested hparams
KL_annealing_steps: kl.annealing_steps
KL_free_nats: kl.free_nats
MADE_loss: aux.MADE
MADE_loss_tl: aux.MADE_tl
attention: attention
batch_size: batch_size
beam_width: beam_width
bidirectional: bidirectional
bow_loss: aux.bow
bow_loss_tl: aux.bow_tl
bpe_codes_prefix: bpe.codes_prefix
bpe_merge: bpe.merge
cell_type: cell_type
count_MADE_loss: aux.count_MADE
count_MADE_loss_tl: aux.count_MADE_tl
criterion: criterion
decoder_style: dec.style
detokenize: detokenize
draw_translations: draw_translations
dropout: dropout
emb_init_scale: emb.init_scale
emb_size: emb.size
encoder_style: enc.style
evaluate_every: evaluate_every
feed_z: feed_z
gen_l2_weight: gen.l2_weight
gen_lr: gen.lr
gen_optimizer: gen.opt
hidden_size: hidden.size
ibm1_loss: aux.ibm1
inf_conditioning: inf.conditioning
inf_encoder_style: inf.encoder_style
inf_z_l2_weight: inf.l2_weight
inf_z_lr: inf.lr
inf_z_optimizer: inf.opt
inf_share_embeddings: inf.share_embeddings
interactive_translation: translation.interactive
latent_size: latent.size
latent_sizes: latent.sizes
length_penalty_factor: length_penalty_factor
lowercase: lowercase
lr_reduce_cooldown: lr.reduce_cooldown
lr_reduce_factor: lr.reduce_factor
lr_reduce_patience: lr.reduce_patience
lr_scheduler: lr.scheduler
lr_warmup: lr.warmup
max_decoding_length: dec.max_length
max_gradient_norm: max_gradient_norm
max_pooling_states: max_pooling_states
max_sentence_length: max_sentence_length
max_vocab_size: vocab.max_size
min_lr: lr.min
minimum_desired_rate: kl.mdr
mixture_likelihood: likelihood.mixture
mixture_likelihood_dir_prior: likelihood.mixture_dir_prior
model_checkpoint: model.checkpoint
model_type: model.type
mono_src: mono_src
mono_tgt: mono_tgt
num_dec_layers: dec.num_layers
num_enc_layers: enc.num_layers
num_epochs: num_epochs
output_dir: output_dir
patience: patience
posterior: posterior.type
postprocess_ref: postprocess_ref
print_every: print_every
prior: prior.type
prior_params: prior.params
recase: recase
sample_decoding: dec.sample
share_vocab: vocab.shared
show_raw_output: show_raw_output
shuffle_lm: aux.shuffle_lm
shuffle_lm_keep_bpe: aux.shuffle_lm_keep_bpe
shuffle_lm_tl: aux.shuffle_lm_tl
split_sentences: split_sentences
src: src
subword_token: subword_token
tgt: tgt
tied_embeddings: emb.tied
tokenize: tokenize
training_prefix: training_prefix
transformer_heads: transformer.heads
transformer_hidden: transformer.hidden
translation_input_file: translation.input_file
translation_output_file: translation.output_file
translation_ref_file: translation.ref_file
truecaser_prefix: truecaser_prefix
use_gpu: use_gpu
use_memmap: use_memmap
validation_prefix: validation_prefix
verbose: verbose
vocab_min_freq: vocab.min_freq
vocab_prefix: vocab.prefix
word_dropout: word_dropout
